name: Gather Stats

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes

permissions:
  contents: write

jobs:
  gather-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Run gather_stats.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        ./gather_stats.sh 60   # Gather stats for PRs that were changed in the last 12 minutes

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data
        git commit -m 'Update data/'

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
